-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 产品咨询记录表
CREATE TABLE IF NOT EXISTS public.inquiries (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(100) NOT NULL,
  phone VARCHAR(20) NOT NULL,
  email VARCHAR(255),
  company VARCHAR(200),
  product_id VARCHAR(100),
  product_name VARCHAR(200),
  message TEXT,
  status VARCHAR(50) DEFAULT 'pending',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 访客统计表
CREATE TABLE IF NOT EXISTS public.visitors (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ip_address VARCHAR(50),
  user_agent TEXT,
  page_path VARCHAR(500),
  referrer VARCHAR(500),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 产品浏览记录表
CREATE TABLE IF NOT EXISTS public.product_views (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id VARCHAR(100) NOT NULL,
  product_name VARCHAR(200),
  visitor_ip VARCHAR(50),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 启用RLS
ALTER TABLE public.inquiries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.visitors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_views ENABLE ROW LEVEL SECURITY;

-- 创建策略：允许匿名用户提交咨询
CREATE POLICY "允许匿名用户提交咨询" ON public.inquiries
  FOR INSERT WITH CHECK (true);

-- 创建策略：允许匿名用户查看自己的咨询
CREATE POLICY "允许匿名用户查看咨询列表" ON public.inquiries
  FOR SELECT USING (true);

-- 创建策略：允许匿名用户记录访客信息
CREATE POLICY "允许匿名用户记录访客" ON public.visitors
  FOR INSERT WITH CHECK (true);

-- 创建策略：允许匿名用户记录产品浏览
CREATE POLICY "允许匿名用户记录产品浏览" ON public.product_views
  FOR INSERT WITH CHECK (true);

-- 创建策略：允许匿名用户查看产品浏览统计
CREATE POLICY "允许匿名用户查看产品浏览统计" ON public.product_views
  FOR SELECT USING (true);

-- 创建更新时间触发器
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_inquiries_updated_at
  BEFORE UPDATE ON public.inquiries
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();